<script lang="ts">
	let { data, form } = $props();
	const engine = data.engine;
	const details = data.connectionDetails || {};
	const activeSessions = engine.id === 'mcp' ? data.sessions.filter((session: any) => String(session.status || 'active') === 'active').length : 0;
</script>

<svelte:head><title>{engine.name} Connections · OrbitFS Engine Host</title><meta name="robots" content="noindex,nofollow" /></svelte:head>
<div class="shell">
	<header><a href="/engines">OrbitFS Engine Host</a><nav><a href={`/engines/${engine.id}`}>{engine.name}</a><b>Connections</b></nav></header>
	<main>
		<div class="title"><div><small>CONNECTIONS</small><h1>{engine.fullName}</h1><p>Actual Panel, client and session connections.</p></div><a href={`/engines/${engine.id}`}>Back to engine</a></div>
		{#if form?.error}<div class="notice error">{form.error}</div>{/if}{#if form?.message}<div class="notice ok">{form.message}</div>{/if}
		<div class="facts"><span><small>Panel</small><b>{engine.panelUrl || 'Not linked'}</b></span><span><small>Workspace</small><b>{engine.workspaceName || engine.workspaceId || 'Not assigned'}</b></span><span><small>Host</small><b>{engine.hostUrl || 'Not linked'}</b></span><span><small>Last sync</small><b>{engine.lastSyncAt || 'Never'}</b></span></div>

		{#if engine.id === 'mcp'}
			<section><h2>MCP endpoint</h2><dl><dt>Transport</dt><dd><code>{details.transport || 'Not available'}</code></dd><dt>OAuth authority</dt><dd><code>{details.authority || 'Not available'}</code></dd><dt>Clients</dt><dd>{data.clients.length}</dd><dt>Active sessions</dt><dd>{activeSessions}</dd></dl></section>

			<section><div class="section-title"><h2>Registered clients</h2><span>{data.clients.length}</span></div>{#if data.clients.length}<div class="table clients"><div class="row head"><span>Client</span><span>Status</span><span>Workspaces</span><span>Last seen</span><span>Control</span></div>{#each data.clients as client}<div class="row"><span><b>{client.client_name || client.id}</b><small>{client.id}</small></span><span>{client.status || 'active'}</span><span>{Array.isArray(client.workspace_ids) && client.workspace_ids.length ? client.workspace_ids.length : 'All allowed'}</span><span>{client.last_seen_at ? new Date(client.last_seen_at).toLocaleString() : 'Never'}</span><span><form method="POST" action="?/client"><input type="hidden" name="clientId" value={client.id}/><input type="hidden" name="action" value={client.status === 'disabled' ? 'enable' : 'disable'}/><button>{client.status === 'disabled' ? 'Enable' : 'Disable'}</button></form></span></div>{/each}</div>{:else}<p class="empty">No MCP clients registered.</p>{/if}</section>

			<section><div class="section-title"><h2>Sessions</h2><span>{data.sessions.length}</span></div>{#if data.sessions.length}<div class="table sessions"><div class="row head"><span>User</span><span>Client</span><span>Status</span><span>Requests</span><span>Control</span></div>{#each data.sessions as session}<div class="row"><span>{session.username || session.user_id || 'Unknown'}</span><span>{session.client_id || session.provider || '—'}</span><span>{session.status || 'active'}</span><span>{session.request_count || 0}</span><span>{#if String(session.status || 'active') === 'active'}<form method="POST" action="?/session"><input type="hidden" name="sessionId" value={session.id}/><button>Disconnect</button></form>{:else}—{/if}</span></div>{/each}</div>{:else}<p class="empty">No MCP sessions recorded.</p>{/if}</section>
		{:else}
			<section><h2>Connection details</h2><pre>{JSON.stringify(details, null, 2)}</pre></section>
		{/if}
		<div class="links"><a href={`/engines/${engine.id}/setup`}>First-time setup</a><a href={`/engines/${engine.id}/configuration`}>Configuration</a>{#if engine.id === 'mcp'}<a href={`/engines/${engine.id}/oauth`}>OAuth</a>{/if}<a href={`/engines/${engine.id}/runtime`}>Runtime</a></div>
	</main>
</div>
<style>
	:global(html){background:#090b0e;color:#eee;font-family:Inter,ui-sans-serif,system-ui}:global(body){margin:0}.shell{min-height:100vh}header{height:54px;border-bottom:1px solid #25282d;display:flex;align-items:center;justify-content:space-between;padding:0 22px;background:#0b0d10}header>a{color:#fff;text-decoration:none;font-weight:700;font-size:13px}nav{display:flex;gap:8px;font-size:11px;color:#777}nav a{color:#aaa;text-decoration:none}main{max-width:1040px;margin:0 auto;padding:34px 18px 60px}.title{display:flex;justify-content:space-between;align-items:end;border-bottom:1px solid #25282d;padding-bottom:18px}.title small{font-size:9px;color:#777;letter-spacing:.14em}.title h1{margin:4px 0 5px;font-size:28px}.title p{margin:0;color:#8b9198;font-size:12px}.title>a{color:#aaa;text-decoration:none;font-size:11px}.notice{padding:10px 12px;border:1px solid #343940;margin:14px 0;font-size:11px}.notice.error{border-color:#6a3030;color:#f3b4b4}.notice.ok{border-color:#2f6646;color:#9de2b8}.facts{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid #25282d;margin:18px 0}.facts span{padding:10px;border-right:1px solid #25282d;min-width:0}.facts span:last-child{border-right:0}.facts small{display:block;color:#737980;font-size:8px;text-transform:uppercase}.facts b{display:block;margin-top:3px;font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}section{border:1px solid #25282d;padding:16px;margin-top:14px;background:#0c0f12}section h2{font-size:15px;margin:0}.section-title{display:flex;justify-content:space-between}.section-title span{font-size:10px;color:#777}dl{display:grid;grid-template-columns:140px 1fr;gap:8px 12px;font-size:10px;margin:14px 0 0}dt{color:#777}dd{margin:0;min-width:0}code{word-break:break-all;color:#c9ccd1}.table{overflow:auto;margin-top:12px}.row{min-width:720px;display:grid;gap:10px;align-items:center;padding:9px 6px;border-top:1px solid #23262b;font-size:10px}.clients .row{grid-template-columns:1.8fr .7fr .7fr 1.2fr .7fr}.sessions .row{grid-template-columns:1.3fr 1.4fr .8fr .6fr .8fr}.row.head{color:#70767d;text-transform:uppercase;font-size:8px;border-top:0}.row span:first-child{display:grid}.row small{font-size:8px;color:#686e75}.row form{margin:0}button{background:#15181c;border:1px solid #3a3f46;color:#ddd;padding:6px 9px;font-size:9px;cursor:pointer}.empty{font-size:10px;color:#777}pre{font-size:9px;overflow:auto;color:#aaa}.links{display:flex;gap:7px;flex-wrap:wrap;margin-top:16px}.links a{border:1px solid #30343a;color:#aaa;text-decoration:none;padding:7px 9px;font-size:9px}@media(max-width:700px){.facts{grid-template-columns:1fr}.facts span{border-right:0;border-bottom:1px solid #25282d}.facts span:last-child{border-bottom:0}.title{align-items:start;flex-direction:column}dl{grid-template-columns:1fr}}
</style>