import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { WebStandardStreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/webStandardStreamableHttp.js';
import { registerAppResource, registerAppTool, RESOURCE_MIME_TYPE } from '@modelcontextprotocol/ext-apps/server';
import { AsyncLocalStorage } from 'node:async_hooks';
import { z } from 'zod';
import widgetHtml from '../ui/widget.html?raw';
import studioWidgetHtml from '../ui/studio-widget.html?raw';
import { authenticateMcpAccessToken } from '$lib/server/mcp-oauth';
import { assertMcpLicensed } from '$lib/server/mcp-cloud';
import { getStartup, getPresets, getPresetMetadata, getPresetBundles, listMcpProjects, projectBundleAssignments, listContextBundles } from '$lib/server/mcp-workspace-state';
import { getSupabaseAdmin } from '$lib/server/supabase';
import {
  accessibleMcpWorkspaces, auditSystemCommand, browseWorkspace, chooseWorkspace, clearActiveContext,
  compactContext, createCloudMcpIdentity, createFolderCloud, deleteEntryCloud, editFileCloud,
  exportProfilesCloud, fileInfoCloud, getActiveContext, inspectContextChanges, knowledgeImpactCloud,
  knowledgeLineageCloud, knowledgeOverviewCloud, knowledgeSectionCloud, loadContextBundleCloud,
  loadFileIntoContext, loadFolderIntoContext, loadKnowledgeIntoContext, loadProfileIntoContext,
  moveEntryCloud, profileCommandCloud, readFileCloud, readManyCloud, refreshPermissionsCloud,
  reloadChangedContext, removeContextItem, resolveKnowledgeTargetCloud, runStartupCloud,
  searchFilesCloud, searchKnowledgeCloud, systemStatusCloud, unloadContextBundleCloud,
  uploadChatGptFileCloud, viewProfileCloud, writeFileCloud, listProfilesCloud
} from './mcp-live-cloud';import {
  analyseStudioRouting, appendStudioCloud, buildStudioUiState, createDocumentFromRecord,
  listStudioLinks, manageStudioLink, setStudioModeCloud, studioApprovals, studioSessionCloud,
  studioVentProfile, submitStudioApproval
} from './mcp-studio-cloud';
import {
  createStudioDocument, getStudioDocument, listStudioDocuments, restoreStudioRevision,
  setStudioLifecycle, studioRevisions, studioSchema, updateStudioDocument
} from '$lib/server/studio-cloud';
import { parseProfileUpload } from '$lib/server/profile-import';

const SERVER_NAME='OrbitFS MCP', SERVER_VERSION='1.5.0';
const optimizedWidgetHtml=widgetHtml.replace(/setTimeout\(async\(\)=>\{try\{await call\('orbitfs_ui_state',[\s\S]*?\}\},0\);(?=\s*<\/script>)/,'');
const requestIdentity=new AsyncLocalStorage<any>();
const activeIdentity=()=>{const identity=requestIdentity.getStore();if(!identity)throw Object.assign(new Error('MCP request identity is unavailable'),{status:500,code:'MCP_IDENTITY_UNAVAILABLE'});return identity;};
const identityProxy:any=new Proxy({}, {
  get(_target,property){return activeIdentity()[property as any];},
  set(_target,property,value){activeIdentity()[property as any]=value;return true;},
  has(_target,property){return property in activeIdentity();},
  ownKeys(){return Reflect.ownKeys(activeIdentity());},
  getOwnPropertyDescriptor(_target,property){const descriptor=Object.getOwnPropertyDescriptor(activeIdentity(),property);return descriptor?{...descriptor,configurable:true}:{configurable:true,enumerable:true,writable:true,value:activeIdentity()[property as any]};}
});
let sharedRuntimePromise:Promise<{server:McpServer;transport:WebStandardStreamableHTTPServerTransport}>|null=null;
const outputSchema=z.object({ok:z.boolean().optional(),message:z.string().optional(),workspaceId:z.string().optional()}).passthrough();
const textResult=(message:string,data:any={},meta:any={})=>({content:[{type:'text' as const,text:message}],structuredContent:{ok:true,message,...data},_meta:{...meta,orbitfsUiState:data}});
const contentResult=(content:string,data:any={},meta:any={})=>({content:[{type:'text' as const,text:content}],structuredContent:{ok:true,...data},_meta:{...meta,orbitfsUiState:data}});
const asError=(error:any)=>({content:[{type:'text' as const,text:String(error?.message||error||'OrbitFS request failed')}],isError:true});
const requireAdmin=(identity:any)=>{if(!['owner','admin'].includes(String(identity.role||'').toLowerCase()))throw Object.assign(new Error('System Owner or Admin required'),{status:403,code:'SYSTEM_ROLE_REQUIRED'});};

function registerResources(server:McpServer){
  const home='ui://orbitfs/home-v8.html', studio='ui://orbitfs/studio-v8.html';
  const homeMeta:any={ui:{prefersBorder:true,csp:{connectDomains:[],resourceDomains:[]}},'openai/widgetDescription':'OrbitFS workspace files, context and upload controls','openai/widgetPrefersBorder':true};
  for(const uri of [home,'ui://orbitfs/home-v7.html']) registerAppResource(server,'OrbitFS Home',uri,{description:'OrbitFS workspace files, context and upload controls',mimeType:RESOURCE_MIME_TYPE,_meta:homeMeta},async()=>({contents:[{uri,mimeType:RESOURCE_MIME_TYPE,text:optimizedWidgetHtml,_meta:homeMeta}]}));  const studioMeta:any={ui:{prefersBorder:true,csp:{connectDomains:[],resourceDomains:[]}},'openai/widgetDescription':'OrbitFS Studio chat-first writing and documentation','openai/widgetPrefersBorder':true};
  for(const uri of [studio,'ui://orbitfs/studio-v7.html','ui://orbitfs/studio-v6.html','ui://orbitfs/studio-v5.html','ui://orbitfs/studio-v4.html']){
    registerAppResource(server,'OrbitFS Studio',uri,{description:'OrbitFS Studio chat-first writing and documentation',mimeType:RESOURCE_MIME_TYPE,_meta:studioMeta},async()=>({contents:[{uri,mimeType:RESOURCE_MIME_TYPE,text:studioWidgetHtml,_meta:studioMeta}]}));
  }
  return {
    homeMeta:{ui:{resourceUri:home},'openai/outputTemplate':home,'openai/widgetAccessible':true,'openai/widgetPrefersBorder':true,'openai/widgetDescription':'OrbitFS workspace files, context and upload controls'},
    studioMeta:{ui:{resourceUri:studio},'openai/outputTemplate':studio,'openai/widgetAccessible':true,'openai/widgetPrefersBorder':true,'openai/widgetDescription':'OrbitFS Studio chat-first writing and documentation'},
    appOnly:{'openai/widgetAccessible':true,ui:{visibility:['app']}}
  };
}

async function buildStartupUiConfig(identity:any, workspaceId:string, strength:string, projectId:string|undefined, profiles:any) {
  const [startup, projects] = await Promise.all([getStartup(workspaceId), listMcpProjects(workspaceId)]);
  const selectedProject = projectId
    ? projects.find((p:any)=>String(p.id)===String(projectId)) || null
    : projects.find((p:any)=>(startup.projectIds||[]).map(String).includes(String(p.id))) || null;
  const scopeId = selectedProject?.id || null;
  const [presets, presetMetadata, presetBundles] = await Promise.all([
    getPresets(workspaceId, scopeId), getPresetMetadata(workspaceId, scopeId), getPresetBundles(workspaceId, scopeId)
  ]);
  const preset = strength || startup.strength || 'medium';
  const selectedPreset = presets?.[preset] || {};
  const byProfile = new Map((profiles.profiles||[]).map((p:any)=>[String(p.id),p]));
  const byBundle = new Map((profiles.profileBundles||[]).map((b:any)=>[String(b.id),b]));
  const hydrateBundle = (id:any) => {
    const bundle:any = byBundle.get(String(id));
    return bundle ? { ...bundle, profiles:(bundle.profileIds||[]).map((pid:any)=>byProfile.get(String(pid))).filter(Boolean) } : null;
  };
  const defaultProfiles = (startup.defaultProfileIds||[]).map((id:any)=>byProfile.get(String(id))).filter(Boolean);
  const defaultProfileBundles = (startup.defaultProfileBundleIds||[]).map(hydrateBundle).filter(Boolean);
  const presetProfiles = (selectedPreset.profileIds||[]).map((id:any)=>byProfile.get(String(id))).filter(Boolean);
  const presetProfileBundles = (selectedPreset.profileBundleIds||[]).map(hydrateBundle).filter(Boolean);
  const projectBundles = selectedProject ? await projectBundleAssignments(String(selectedProject.id)) : [];
  const assignedMap = new Map<string,any>();
  for (const item of [...(presetBundles?.[preset]||[]), ...projectBundles]) assignedMap.set(String(item.bundleId), item);
  const assignedContextBundles = [...assignedMap.values()];
  return {
    startup,
    projects: projects.map((p:any)=>({id:String(p.id),name:p.name,description:p.description||''})),
    project: selectedProject,
    presetMetadata,
    defaultItems: startup.defaultItems||[],
    projectItems: selectedProject?.items||[],
    presetItems: selectedPreset.items||[],
    assignedBundles: assignedContextBundles,
    instructions: selectedProject?.instructions || startup.instructions || '',
    aiBehaviour: selectedProject?.ai_behaviour || startup.aiBehaviour || '',
    startupSelection:{ defaultItems:startup.defaultItems||[], projectItems:selectedProject?.items||[], presetItems:selectedPreset.items||[], defaultProfiles, defaultProfileBundles, presetProfiles, presetProfileBundles, assignedContextBundles }
  };
}


async function uiState(identity:any,workspaceId?:string,strength?:string,projectId?:string){
  const requested = workspaceId && workspaceId !== 'default' ? workspaceId : undefined;
  let picked:any=await chooseWorkspace(identity,requested);
  if (!requested && picked.workspace?.mcp_ui_enabled === false) {
    const preferred = picked.workspaces.find((w:any)=>w.mcp_ui_enabled !== false);
    if (preferred) picked = await chooseWorkspace(identity,String(preferred.id));
  }
  const ws=picked.workspace;
  const uiWorkspaces=picked.workspaces.filter((w:any)=>w.mcp_ui_enabled !== false);
  const [receipt,bundles,profiles]=await Promise.all([
    getActiveContext(identity,ws.id),
    listContextBundles(ws.id).catch(()=>[]),
    listProfilesCloud(identity,ws.id).catch(()=>({enabled:false,profiles:[],profileBundles:[],settings:{},permissions:{},slots:{master:null,additional:null}}))
  ]);
  const changes=await inspectContextChanges(identity,ws.id,receipt);
  const config=strength?await buildStartupUiConfig(identity,ws.id,strength,projectId,profiles).catch(()=>null):null;
  return {
    workspaceId:ws.id,workspaceName:ws.name,
    workspaces:uiWorkspaces.map((w:any)=>({id:String(w.id),name:w.name,status:w.status||'active',permission:w.permission})),
    strength:strength||null,projectId:projectId||config?.project?.id||null,
    dashboard:{user:{username:identity.username,systemRole:identity.role},workspace:{id:String(ws.id),name:ws.name,status:ws.status||'active',role:ws.permission||ws.role||'viewer'}},
    context:compactContext(receipt,changes.changedFiles),activeContext:receipt,activeFiles:receipt?.files||[],bundles,
    profiles:profiles.profiles||[],profileBundles:profiles.profileBundles||[],settings:profiles.settings||{},permissions:profiles.permissions||{},slots:profiles.slots||{master:null,additional:null},
    profileSystemEnabled:profiles.enabled===true,canWrite:identity.scopes?.has?.('orbitfs:write')&&identity.clientPermissions?.write!==false,
    ...(config?{config}:{})
  };
}

function createServer(identity:any){
  const server=new McpServer({name:SERVER_NAME,version:SERVER_VERSION});
  const {homeMeta,studioMeta,appOnly}=registerResources(server);
  const ro={readOnlyHint:true,idempotentHint:true,destructiveHint:false,openWorldHint:false};
  const rw={readOnlyHint:false,idempotentHint:false,destructiveHint:false,openWorldHint:false};
  const destructive={readOnlyHint:false,idempotentHint:false,destructiveHint:true,openWorldHint:false};
  const reg=(name:string,title:string,description:string,inputSchema:any,handler:any,annotations:any=ro,meta:any={})=>server.registerTool(name,{title,description,inputSchema,outputSchema,annotations,_meta:meta},async(args:any)=>{try{return await handler(args);}catch(e){return asError(e);}});
  reg('workspace','Current OrbitFS workspace','Show the currently selected OrbitFS workspace.',{},async()=>{const p=await chooseWorkspace(identity);return textResult(`Workspace: ${p.workspace.name}`,{workspaceId:p.workspace.id,workspaceName:p.workspace.name});});
  reg('loadworkspace','Load OrbitFS workspace','Switch the current OrbitFS workspace by name, id, or visible workspace number.',{name:z.string().min(1)},async({name}:any)=>{const p:any=await chooseWorkspace(identity,name);if(p.matches)return textResult(p.matches.map((w:any,i:number)=>`${i+1}. ${w.name}`).join('\n'),{matches:p.matches.map((w:any)=>({id:w.id,name:w.name}))});return textResult(`Workspace loaded: ${p.workspace.name}`,{workspaceId:p.workspace.id,workspaceName:p.workspace.name});},rw);
  registerAppTool(server,'orbitfs',{title:'Open OrbitFS',description:'Open the OrbitFS embedded UI. Only call when the user explicitly asks to open OrbitFS.',inputSchema:{workspaceId:z.string().optional(),strength:z.enum(['low','medium','high','custom1','custom2']).optional(),projectId:z.string().optional()},annotations:ro,_meta:homeMeta},async({workspaceId,strength,projectId}:any)=>({content:[{type:'text',text:'OrbitFS opened.'}],structuredContent:{ok:true,message:'OrbitFS opened.'},_meta:{...homeMeta,orbitfsUiState:await uiState(identity,workspaceId,strength,projectId)}}));
  registerAppTool(server,'studio',{title:'Open Studio',description:'Open the OrbitFS Studio ChatGPT UI when the user asks to open, browse, journal in, or work with Studio.',inputSchema:{workspaceId:z.string().optional(),view:z.enum(['home','journals','documents','library']).optional()},annotations:ro,_meta:studioMeta},async({workspaceId,view='home'}:any)=>{const p:any=await chooseWorkspace(identity,workspaceId),state:any=await buildStudioUiState(identity,p.workspace.id);state.initialView=view;state.workspaces=p.workspaces.map((w:any)=>({id:String(w.id),name:w.name,status:w.status||'active'}));return {content:[{type:'text',text:'Studio opened.'}],structuredContent:{ok:true,message:'Studio opened.',workspaceId:p.workspace.id},_meta:{...studioMeta,studioUiState:state}};});
  registerAppTool(server,'ventmode',{title:'Open Studio Vent Mode',description:'Compatibility command: ventmode. Open OrbitFS Studio with Vent Mode enabled for the current or selected workspace.',inputSchema:{workspaceId:z.string().optional()},annotations:rw,_meta:studioMeta},async({workspaceId}:any)=>{const p:any=await chooseWorkspace(identity,workspaceId);setStudioModeCloud(identity,p.workspace.id,'vent');const state:any=await buildStudioUiState(identity,p.workspace.id);state.initialView='journals';state.workspaces=p.workspaces.map((w:any)=>({id:String(w.id),name:w.name,status:w.status||'active'}));return {content:[{type:'text',text:'Studio opened in Vent Mode.'}],structuredContent:{ok:true,message:'Studio opened in Vent Mode.',workspaceId:p.workspace.id},_meta:{...studioMeta,studioUiState:state}};});
  reg('orbitfs_ui_state','OrbitFS internal UI state','Internal app-only state endpoint for the embedded OrbitFS widget.',{workspaceId:z.string().optional(),strength:z.enum(['low','medium','high','custom1','custom2']).optional(),projectId:z.string().optional()},async({workspaceId,strength,projectId}:any)=>textResult('OrbitFS UI state refreshed.',{}, {...appOnly,orbitfsUiState:await uiState(identity,workspaceId,strength,projectId)}),ro,appOnly);
  reg('refresh_ui','Refresh OrbitFS UI','Refresh OrbitFS workspace access and rehydrate the embedded UI.',{workspaceId:z.string().optional(),strength:z.enum(['low','medium','high','custom1','custom2']).optional(),projectId:z.string().optional()},async({workspaceId,strength,projectId}:any)=>{const perms=await refreshPermissionsCloud(identity),state=await uiState(identity,workspaceId,strength,projectId);return textResult(`OrbitFS refreshed. ${perms.workspaceIds.length} workspace${perms.workspaceIds.length===1?'':'s'} available.`,{workspaceCount:perms.workspaceIds.length}, {...homeMeta,orbitfsUiState:state});});  reg('load_defaults','Load OrbitFS defaults','Load selected workspace default files and profiles into active context.',{workspaceId:z.string(),projectId:z.string().optional(),maxFiles:z.number().int().positive().max(500).optional(),maxCharacters:z.number().int().positive().max(5000000).optional()},async(a:any)=>{const r=await runStartupCloud(identity,a.workspaceId,'medium',a.projectId,true,a.maxFiles||250,a.maxCharacters||1500000);return textResult(r.loaded.length?`Loaded ${r.loaded.length} default item${r.loaded.length===1?'':'s'} into OrbitFS context.`:'No default items are configured for this workspace.',{workspaceId:a.workspaceId,loadedCount:r.loaded.length,charactersLoaded:r.total,errorCount:r.errors.length}, {orbitfsUiState:{workspaceId:a.workspaceId,context:compactContext(r.receipt)}});},rw);
  reg('run_startup','Run OrbitFS workspace startup','Manual startup action. Load always-loaded and selected preset content only when explicitly requested.',{workspaceId:z.string(),strength:z.enum(['low','medium','high','custom1','custom2']),projectId:z.string().optional()},async(a:any)=>{const r=await runStartupCloud(identity,a.workspaceId,a.strength,a.projectId,false,250);return textResult(`Startup loaded ${r.loaded.length} item${r.loaded.length===1?'':'s'} (${r.total} chars)${r.errors.length?`, ${r.errors.length} failed`:''}.`,{workspaceId:a.workspaceId,loadedCount:r.loaded.length,charactersLoaded:r.total,errorCount:r.errors.length},{orbitfsUiState:{workspaceId:a.workspaceId,context:compactContext(r.receipt)}});},rw);
  reg('context_status','OrbitFS context status','Show compact active-context status and whether source files changed.',{workspaceId:z.string()},async({workspaceId}:any)=>{const receipt=await getActiveContext(identity,workspaceId),changes=await inspectContextChanges(identity,workspaceId,receipt),summary=compactContext(receipt,changes.changedFiles);return textResult(`${summary.state} · ${summary.files} items · ${summary.charactersLabel} chars`,{workspaceId,context:summary,changedFiles:changes.changedFiles});});
  reg('context_explain','Explain OrbitFS context','Explain the currently loaded context items, sources, owners and bundle relationships.',{workspaceId:z.string()},async({workspaceId}:any)=>{const r=await getActiveContext(identity,workspaceId);const files=(r?.files||[]).map((x:any)=>({path:x.path,source:x.source,owners:x.contextOwners||[],required:!!x.required,characters:Number(x.characters||0),warning:x.warning||''}));return textResult(files.length?files.map((x:any)=>`- ${x.path} · ${x.source||'manual'} · ${x.characters} chars${x.owners.length?` · ${x.owners.join(', ')}`:''}`).join('\n'):'No active context.',{workspaceId,contextId:r?.contextId||null,items:files,bundles:r?.bundles||[]});});
  reg('get_active_context','Get active OrbitFS context','Return the exact context receipt currently active for a workspace.',{workspaceId:z.string()},async({workspaceId}:any)=>{const r=await getActiveContext(identity,workspaceId),c=await inspectContextChanges(identity,workspaceId,r);return textResult(r?`${(r.files||[]).length} context item(s) active.`:'No active context.',{workspaceId,receipt:r,context:compactContext(r,c.changedFiles)});});
  reg('load_file','Load OrbitFS file','Read one permitted workspace file and append its actual contents to active context.',{workspaceId:z.string(),path:z.string(),maxCharacters:z.number().int().positive().max(1500000).optional()},async(a:any)=>{const r=await loadFileIntoContext(identity,a.workspaceId,a.path,a.maxCharacters||500000);return textResult(r.loaded.length?'Loaded 1 file into OrbitFS context.':'File could not be loaded.',{workspaceId:a.workspaceId,loadedCount:r.loaded.length,errorCount:r.errors.length},{orbitfsUiState:{workspaceId:a.workspaceId,context:compactContext(r.receipt)}});},rw);
  reg('load_folder','Load OrbitFS folder','Recursively read permitted files from a workspace folder and append their contents to active context.',{workspaceId:z.string(),path:z.string(),maxFiles:z.number().int().positive().max(500).optional(),maxCharacters:z.number().int().positive().max(5000000).optional()},async(a:any)=>{const r=await loadFolderIntoContext(identity,a.workspaceId,a.path,a.maxFiles||100,a.maxCharacters||1500000);return textResult(`Loaded ${r.loaded.length} folder item${r.loaded.length===1?'':'s'} into OrbitFS context.`,{workspaceId:a.workspaceId,loadedCount:r.loaded.length,errorCount:r.errors.length,discoveredCount:r.discoveredCount},{orbitfsUiState:{workspaceId:a.workspaceId,context:compactContext(r.receipt)}});},rw);  reg('list_context_bundles','List OrbitFS context bundles','List reusable CCS context bundles available in a workspace.',{workspaceId:z.string()},async({workspaceId}:any)=>{await chooseWorkspace(identity,workspaceId);const bundles=await listContextBundles(workspaceId);return textResult(bundles.length?`${bundles.length} context bundle${bundles.length===1?'':'s'} available.`:'No context bundles configured.',{workspaceId,bundleCount:bundles.length,bundles});});
  reg('load_context_bundle','Load OrbitFS context bundle','Resolve a named context bundle and its dependencies and merge them into active context.',{workspaceId:z.string(),bundleId:z.string(),maxFiles:z.number().int().positive().max(500).optional(),maxCharacters:z.number().int().positive().max(5000000).optional()},async(a:any)=>{const r=await loadContextBundleCloud(identity,a.workspaceId,a.bundleId,a.maxFiles||250,a.maxCharacters||1500000);return textResult(`Loaded context bundle (${r.loaded.length} item${r.loaded.length===1?'':'s'}).`,{workspaceId:a.workspaceId,bundleId:a.bundleId,loadedCount:r.loaded.length,errorCount:r.errors.length},{orbitfsUiState:{workspaceId:a.workspaceId,context:compactContext(r.receipt)}});},rw);
  reg('unload_context_bundle','Unload OrbitFS context bundle','Remove a loaded context bundle ownership from active context.',{workspaceId:z.string(),bundleId:z.string()},async(a:any)=>{const receipt=await unloadContextBundleCloud(identity,a.workspaceId,a.bundleId);return textResult('Context bundle unloaded.',{workspaceId:a.workspaceId,bundleId:a.bundleId},{orbitfsUiState:{workspaceId:a.workspaceId,context:compactContext(receipt)}});},destructive);
  reg('list_workspace_entries','Browse OrbitFS workspace','Internal app-only file/folder browser for the embedded picker.',{workspaceId:z.string(),path:z.string().optional()},async(a:any)=>{const entries=await browseWorkspace(identity,a.workspaceId,a.path||'');return textResult(`${entries.length} item${entries.length===1?'':'s'}`,{workspaceId:a.workspaceId,path:a.path||'',entries});},ro,appOnly);
  reg('view_profile','View OrbitFS profile','Display a permitted OrbitFS profile by id or name.',{workspaceId:z.string(),profileId:z.string().optional(),profileName:z.string().optional(),path:z.string().optional()},async(a:any)=>{const ref=a.profileId||a.profileName||a.path;if(!ref)throw new Error('profileId, profileName, or path is required');const r=await viewProfileCloud(identity,a.workspaceId,ref);return contentResult(r.content,{workspaceId:a.workspaceId,receipt:`Profile ${r.profile?.name||ref} loaded.`,profile:r.profile,characters:r.content.length});});
  reg('list_profiles','List OrbitFS profiles','List profiles available to the current user in a workspace.',{workspaceId:z.string()},async({workspaceId}:any)=>{const r=await listProfilesCloud(identity,workspaceId);return textResult(r.profiles.length?r.profiles.map((p:any,i:number)=>`${i+1}. ${p.name} (${p.type||'profile'})`).join('\n'):'No profiles available.',{workspaceId,profileCount:r.profiles.length,profiles:r.profiles,profileBundles:r.profileBundles||[],settings:r.settings||{},permissions:r.permissions||{},slots:r.slots||{master:null,additional:null}});});
  reg('load_profile','Load OrbitFS profile','Load a permitted profile into the active ChatGPT context.',{workspaceId:z.string(),profileId:z.string(),detail:z.enum(['summary','standard','full']).optional()},async(a:any)=>{const r=await loadProfileIntoContext(identity,a.workspaceId,a.profileId,a.detail||'standard');return textResult(`Loaded profile ${r.item.profileName}.`,{workspaceId:a.workspaceId,profile:{id:a.profileId,name:r.item.profileName}},{orbitfsUiState:{workspaceId:a.workspaceId,context:compactContext(r.receipt)}});},rw);
  reg('remove_context_file','Remove item from OrbitFS context','Remove one loaded file, profile or knowledge item from active context.',{workspaceId:z.string(),path:z.string()},async(a:any)=>{const r=await removeContextItem(identity,a.workspaceId,a.path);return textResult(`Removed ${a.path} from active context.`,{workspaceId:a.workspaceId},{orbitfsUiState:{workspaceId:a.workspaceId,context:compactContext(r)}});},destructive);
  reg('reload_changed_context','Reload changed OrbitFS context','Reload source files changed since active context was created.',{workspaceId:z.string()},async({workspaceId}:any)=>{const r=await reloadChangedContext(identity,workspaceId);return textResult(`Reloaded ${r.loaded.length} changed item${r.loaded.length===1?'':'s'}.`,{workspaceId,reloadedCount:r.loaded.length,errorCount:r.errors.length},{orbitfsUiState:{workspaceId,context:compactContext(r.receipt)}});},rw);
  reg('clear_context','Clear OrbitFS context','Clear active context metadata for a workspace.',{workspaceId:z.string()},async({workspaceId}:any)=>{await clearActiveContext(identity,workspaceId);return textResult('OrbitFS context cleared.',{workspaceId},{orbitfsUiState:{workspaceId,context:compactContext(null)}});},destructive);  reg('search_files','Search OrbitFS files','Search general workspace files by name, path and optionally text content. This is separate from Library knowledge retrieval.',{workspaceId:z.string().optional(),query:z.string().min(1),path:z.string().optional(),includeContent:z.boolean().optional(),maxResults:z.number().int().positive().max(200).optional()},async(a:any)=>{const p:any=await chooseWorkspace(identity,a.workspaceId),r=await searchFilesCloud(identity,p.workspace.id,a.query,a.path||'',a.includeContent===true,a.maxResults||50);return textResult(r.matches.length?r.matches.map((x:any)=>x.path).join('\n'):'No matching files or folders.',{workspaceId:p.workspace.id,...r});});
  reg('read_file','Read OrbitFS file','Read a permitted general workspace file without adding it to active context.',{workspaceId:z.string().optional(),path:z.string(),output:z.enum(['auto','text','base64']).optional(),maxCharacters:z.number().int().positive().max(1500000).optional(),maxBytes:z.number().int().positive().max(20971520).optional()},async(a:any)=>{const p:any=await chooseWorkspace(identity,a.workspaceId),r=await readFileCloud(identity,p.workspace.id,a.path,a.output||'auto',a.maxCharacters||500000,a.maxBytes||20971520);return contentResult(r.encoding==='base64'?`Read ${a.path} as base64 (${r.metadata?.bytes||0} bytes).`:String(r.document?.content||r.content||''),{workspaceId:p.workspace.id,...r});});
  reg('write_file','Write OrbitFS file','Create or update a general OrbitFS workspace file.',{workspaceId:z.string().optional(),path:z.string(),data:z.string(),fileTransferIntent:z.literal('orbitfs').optional(),encoding:z.enum(['utf8','base64']).optional(),mode:z.enum(['create','update','upsert']).optional(),expectedSha256:z.string().regex(/^[a-fA-F0-9]{64}$/).optional(),createParents:z.boolean().optional(),maxBytes:z.number().int().positive().max(262144000).optional()},async(a:any)=>{const p:any=await chooseWorkspace(identity,a.workspaceId);const r=await writeFileCloud(identity,p.workspace.id,a.path,a.data,{encoding:a.encoding||'utf8',mode:a.mode||'create',expectedSha256:a.expectedSha256,createParents:a.createParents,maxBytes:a.maxBytes||104857600,fileTransferIntent:a.fileTransferIntent});return textResult(`${r.created?'Created':'Updated'} ${a.path} (${r.metadata?.bytes||0} bytes).`,{workspaceId:p.workspace.id,...r});},destructive);
  reg('upload_chatgpt_file','Upload ChatGPT file to OrbitFS','Transfer an existing ChatGPT attachment into general OrbitFS workspace storage only with explicit OrbitFS intent.',{file:z.object({download_url:z.string(),file_id:z.string(),mime_type:z.string().optional(),file_name:z.string().optional()}).strict(),intent:z.literal('orbitfs'),directory:z.string().optional(),workspaceId:z.string().optional(),fileName:z.string().optional(),maxBytes:z.number().int().positive().max(262144000).optional()},async(a:any)=>{const p:any=await chooseWorkspace(identity,a.workspaceId),r=await uploadChatGptFileCloud(identity,p.workspace.id,a.file,a.directory||'',a.fileName,a.maxBytes||104857600);return textResult(`Uploaded ${a.file.file_name||a.fileName||'file'} to ${r.metadata.path}.`,{workspaceId:p.workspace.id,...r});},rw);
  reg('create_folder','Create OrbitFS folder','Create one permitted general workspace folder.',{workspaceId:z.string().optional(),path:z.string(),createParents:z.boolean().optional()},async(a:any)=>{const p:any=await chooseWorkspace(identity,a.workspaceId),r=await createFolderCloud(identity,p.workspace.id,a.path,a.createParents===true);return textResult(`Created folder ${a.path}.`,{...r,workspaceId:p.workspace.id});},rw);
  reg('move_entry','Move or rename OrbitFS entry','Move or rename one permitted general workspace file or folder.',{workspaceId:z.string().optional(),sourcePath:z.string(),destinationPath:z.string()},async(a:any)=>{const p:any=await chooseWorkspace(identity,a.workspaceId),r=await moveEntryCloud(identity,p.workspace.id,a.sourcePath,a.destinationPath);return textResult(`Moved ${a.sourcePath} to ${a.destinationPath}.`,{workspaceId:p.workspace.id,sourcePath:a.sourcePath,destinationPath:a.destinationPath});},destructive);
  reg('delete_entry','Move OrbitFS entry to trash','Recoverably delete a permitted general workspace file or folder.',{workspaceId:z.string().optional(),path:z.string()},async(a:any)=>{const p:any=await chooseWorkspace(identity,a.workspaceId),r=await deleteEntryCloud(identity,p.workspace.id,a.path);return textResult(`Moved ${a.path} to recoverable trash.`,{...r,workspaceId:p.workspace.id});},destructive);
  reg('file_info','Get OrbitFS file info','Return current metadata and SHA-256 for one permitted file or folder.',{workspaceId:z.string().optional(),path:z.string(),includeSha256:z.boolean().optional()},async(a:any)=>{const p:any=await chooseWorkspace(identity,a.workspaceId),r=await fileInfoCloud(identity,p.workspace.id,a.path);return textResult(`${r.type}: ${r.path}\n${r.bytes} bytes${r.sha256?`\nSHA-256: ${r.sha256}`:''}`,{workspaceId:p.workspace.id,metadata:r});});
  reg('read_many','Read multiple OrbitFS files','Read multiple permitted general workspace files in one call without adding them to context.',{workspaceId:z.string().optional(),paths:z.array(z.string()).min(1).max(50),maxCharactersPerFile:z.number().int().positive().max(1500000).optional(),maxTotalCharacters:z.number().int().positive().max(3000000).optional(),maxBytesPerFile:z.number().int().positive().max(20971520).optional()},async(a:any)=>{const p:any=await chooseWorkspace(identity,a.workspaceId),loaded:any[]=[],failedFiles:any[]=[],content:any[]=[];let remaining=a.maxTotalCharacters||1500000;for(const filePath of a.paths){if(remaining<=0){failedFiles.push({path:filePath,code:'READ_BUDGET_EXHAUSTED',error:'Total character budget exhausted'});continue;}try{const r:any=await readFileCloud(identity,p.workspace.id,filePath,'text',Math.min(a.maxCharactersPerFile||500000,remaining),a.maxBytesPerFile||20971520),text=String(r.content||'');loaded.push({path:filePath,characters:text.length,truncated:!!r.document?.truncated,...r.metadata});remaining-=text.length;content.push({type:'text' as const,text:`===== ${filePath} =====\n${text}`});}catch(e:any){failedFiles.push({path:filePath,code:e?.code||'READ_FAILED',error:e?.message||String(e)});}}if(!content.length)content.push({type:'text' as const,text:'No files were successfully read.'});return {content,structuredContent:{ok:true,workspaceId:p.workspace.id,requestedCount:a.paths.length,loadedCount:loaded.length,failedCount:failedFiles.length,loaded,failedFiles,charactersRead:loaded.reduce((n:number,x:any)=>n+Number(x.characters||0),0)},_meta:{}};});
  reg('edit_file','Edit OrbitFS file','Safely apply exact text replacements to one permitted UTF-8 file using SHA-256 concurrency protection.',{workspaceId:z.string().optional(),path:z.string(),expectedSha256:z.string().regex(/^[a-fA-F0-9]{64}$/),edits:z.array(z.object({oldText:z.string().min(1),newText:z.string(),expectedOccurrences:z.number().int().positive().max(1000).optional()})).min(1).max(100),dryRun:z.boolean().optional()},async(a:any)=>{const p:any=await chooseWorkspace(identity,a.workspaceId),current:any=await readFileCloud(identity,p.workspace.id,a.path,'text',1500000,20971520);if(String(current.metadata.sha256).toLowerCase()!==String(a.expectedSha256).toLowerCase())throw Object.assign(new Error('File changed since it was read'),{status:409,code:'FILE_VERSION_CONFLICT'});let next=String(current.content||'');const applied:any[]=[];for(const e of a.edits){const count=next.split(e.oldText).length-1,expected=e.expectedOccurrences??1;if(count!==expected)throw Object.assign(new Error(`Expected ${expected} occurrence(s) but found ${count}`),{status:409,code:'EDIT_OCCURRENCE_MISMATCH'});next=next.split(e.oldText).join(e.newText);applied.push({expectedOccurrences:expected,oldCharacters:e.oldText.length,newCharacters:e.newText.length});}if(a.dryRun)return textResult(`Dry run ready: ${applied.length} edit(s) can be applied to ${a.path}.`,{workspaceId:p.workspace.id,dryRun:true,edits:applied,beforeSha256:current.metadata.sha256,beforeBytes:current.metadata.bytes,afterBytes:Buffer.byteLength(next,'utf8')});const saved:any=await writeFileCloud(identity,p.workspace.id,a.path,next,{mode:'update',encoding:'utf8',expectedSha256:a.expectedSha256,maxBytes:20971520});return textResult(`Applied ${applied.length} edit(s) to ${a.path}.`,{workspaceId:p.workspace.id,dryRun:false,edits:applied,beforeSha256:current.metadata.sha256,afterSha256:saved.metadata.sha256,beforeBytes:current.metadata.bytes,afterBytes:saved.metadata.bytes});},destructive);
  reg('save_profile_changes','Save OrbitFS profile changes','Update a structured OrbitFS Profile or queue the change for workspace approval when direct edit permission is unavailable.',{workspaceId:z.string(),profileId:z.string(),patch:z.record(z.string(),z.any()),summary:z.string().optional()},async(a:any)=>{const r=await profileCommandCloud(identity,a.workspaceId,'edit',{patch:a.patch},a.profileId,a.summary||'Profile edit requested from ChatGPT');return textResult(r.applied?'Profile changes saved.':'Profile changes queued for approval.',{workspaceId:a.workspaceId,profileId:a.profileId,...r});},rw);
  reg('create_profile','Create OrbitFS profile','Create a new structured Base Profile or queue it for approval when required.',{workspaceId:z.string(),profile:z.record(z.string(),z.any()),summary:z.string().optional()},async(a:any)=>{const r=await profileCommandCloud(identity,a.workspaceId,'create',{profile:a.profile},null,a.summary||'');return textResult(r.applied?'Profile create completed.':'Profile create queued for approval.',{workspaceId:a.workspaceId,...r});},rw);
  reg('archive_profile','Archive OrbitFS profile','Archive a structured Profile using the recoverable profile lifecycle.',{workspaceId:z.string(),profileId:z.string(),summary:z.string().optional()},async(a:any)=>{const r=await profileCommandCloud(identity,a.workspaceId,'archive',{},a.profileId,a.summary||'');return textResult(r.applied?'Profile archive completed.':'Profile archive queued for approval.',{workspaceId:a.workspaceId,profileId:a.profileId,...r});},destructive);
  reg('repair_profiles','Repair or migrate OrbitFS profiles','Normalize structured Profiles to the current cloud schema and repair Profile state.',{workspaceId:z.string(),summary:z.string().optional()},async(a:any)=>{const r=await profileCommandCloud(identity,a.workspaceId,'repair',{},null,a.summary||'');return textResult(r.applied?'Profile repair/migration completed.':'Profile repair queued for approval.',{workspaceId:a.workspaceId,...r});},rw);
  reg('import_profile','Import OrbitFS profile JSON or ZIP','Import Profile data or a ChatGPT profile attachment into structured Supabase Profile storage.',{workspaceId:z.string(),file:z.object({download_url:z.string(),file_id:z.string(),mime_type:z.string().optional(),file_name:z.string().optional()}).strict().optional(),profileData:z.any().optional(),intent:z.literal('orbitfs').optional(),maxBytes:z.number().int().positive().max(104857600).optional()},async(a:any)=>{if(Boolean(a.file)===Boolean(a.profileData))throw new Error('Provide exactly one of file or profileData');let payload=a.profileData;if(a.file){if(a.intent!=='orbitfs')throw new Error('Explicit OrbitFS import intent is required');const response=await fetch(a.file.download_url);if(!response.ok)throw new Error(`ChatGPT file download failed with HTTP ${response.status}`);const buffer=Buffer.from(await response.arrayBuffer());if(buffer.length>(a.maxBytes||104857600))throw new Error('Profile import file is too large');payload=await parseProfileUpload(buffer,a.file.file_name||'Imported profile',a.file.mime_type||'');}const r=await profileCommandCloud(identity,a.workspaceId,'import',payload,null,'Import profile data');return textResult(r.applied?'Profile import completed.':'Profile import queued for approval.',{workspaceId:a.workspaceId,...r});},destructive);
  reg('export_profile','Export OrbitFS profile JSON or Markdown','Export one permitted structured Profile, or all permitted Profiles.',{workspaceId:z.string(),profileId:z.string().optional(),format:z.enum(['json','md']).optional()},async(a:any)=>{const r=await exportProfilesCloud(identity,a.workspaceId,a.profileId),format=a.format||'json';const profileText=(p:any)=>[`# PROFILE - ${p.name||'Untitled'}`,`Profile type: ${p.type||'person-master'}`,`Status: ${p.status||'active'}`,...(p.sections||[]).filter((s:any)=>s?.removed!==true&&s?.canRead!==false).map((s:any)=>`\n## ${s.title||s.id}\n${s.content||''}`)].join('\n');const body=format==='md'?r.profiles.map(profileText).join('\n\n---\n\n'):JSON.stringify(a.profileId?r.profiles[0]:r,null,2);return contentResult(body,{workspaceId:a.workspaceId,profileCount:r.profiles.length,format});});  reg('knowledge_overview','OrbitFS knowledge overview','Read the current central Base Library knowledge map for a workspace. CCS remains the separate context-grouping system.',{workspaceId:z.string()},async({workspaceId}:any)=>{const data:any=await knowledgeOverviewCloud(identity,workspaceId),items=(data.items||[]).map((x:any)=>({id:x.id,name:x.name,kind:x.kind,category:x.knowledgeArchitecture?.policy?.category||x.category||'',purposes:x.purposes||[],aliases:x.aliases||[],roles:x.roles||[],lifecycleState:x.effectiveLifecycleState||x.lifecycleState||'unclassified',currentTarget:x.currentTarget===true,targetPriority:Number(x.targetPriority||0),importance:x.importance??.5,status:x.status||'active',recordCount:x.recordCount||0,sectionCount:x.sectionCount||0,factCount:x.factCount||0,source:x.source}));return textResult(`OrbitFS Base Library · ${items.length} knowledge item${items.length===1?'':'s'}${items.length?'\n\n'+items.map((x:any)=>`- ${x.name}${x.category?` · ${x.category}`:''} · ${x.recordCount} records · ${x.sectionCount} sections`).join('\n'):''}`,{workspaceId,stats:data.stats||{},items});});
  reg('search_knowledge','Search OrbitFS knowledge','Query the central Base Library and return only relevant indexed sections under a strict character budget. Retrieval follows current Library ranking and Knowledge Setup policy.',{workspaceId:z.string(),query:z.string().max(500),itemIds:z.array(z.string()).max(100).optional(),sectionIds:z.array(z.string()).max(250).optional(),limit:z.number().int().positive().max(50).optional(),maxCharacters:z.number().int().min(500).max(50000).optional()},async(a:any)=>{const r:any=await searchKnowledgeCloud(identity,a.workspaceId,a);const results=r.results||[];return {content:results.length?results.map((x:any)=>({type:'text' as const,text:`===== ${x.itemName} > ${x.sectionTitle} =====\n${x.content}`})):[{type:'text' as const,text:'No matching Base Library knowledge was found.'}],structuredContent:{ok:true,message:`${results.length} knowledge section${results.length===1?'':'s'} returned (${r.returnedChars||0} chars).`,workspaceId:a.workspaceId,query:a.query,resultCount:results.length,returnedChars:r.returnedChars||0,results:results.map(({content,...x}:any)=>x)},_meta:{}};});
  reg('get_knowledge_section','Read OrbitFS knowledge section','Read one exact indexed Base Library section by stable Knowledge Item ID and Section ID.',{workspaceId:z.string(),itemId:z.string(),sectionId:z.string()},async(a:any)=>{const r:any=await knowledgeSectionCloud(identity,a.workspaceId,a.itemId,a.sectionId),label=`${r.item?.name||a.itemId} > ${r.section?.title||a.sectionId}`;return contentResult(`===== ${label} =====\n${r.content||''}`,{workspaceId:a.workspaceId,itemId:a.itemId,sectionId:a.sectionId,section:r.section,entities:r.entities||[],events:r.events||[],facts:r.facts||[],relations:r.factRelations||[]});});
  reg('load_knowledge_item','Load canonical OrbitFS knowledge item','Load one current canonical Library/Profile Knowledge Item directly into active context.',{workspaceId:z.string(),itemId:z.string()},async(a:any)=>{const r:any=await loadKnowledgeIntoContext(identity,a.workspaceId,a.itemId,500000);return textResult(`Loaded ${r.item?.name||a.itemId} from the Base Library.`,{workspaceId:a.workspaceId,itemId:a.itemId,itemName:r.item?.name,lifecycleState:r.item?.lifecycleState,warning:r.item?.warning||'',characterCount:r.item?.characters||0},{orbitfsUiState:{workspaceId:a.workspaceId,context:compactContext(r.receipt)}});},rw);
  reg('resolve_knowledge_target','Resolve OrbitFS knowledge destination','Resolve a configured Base Library destination role. This is read-only and does not apply a change.',{workspaceId:z.string(),role:z.string().max(64)},async(a:any)=>{const r:any=await resolveKnowledgeTargetCloud(identity,a.workspaceId,a.role),target=r.recommended;return textResult(target?`${r.definition?.label||a.role}: ${target.name} · ${target.lifecycleState||'unclassified'}${r.ambiguousCurrent?' · WARNING: multiple Current targets':''}`:`No writable Base Library target is configured for ${a.role}.`,{workspaceId:a.workspaceId,role:a.role,...r});});
  reg('get_knowledge_lineage','Read OrbitFS knowledge lineage','Resolve the visible version chain, current version and derived-from relationships for one Knowledge Item.',{workspaceId:z.string(),itemId:z.string()},async(a:any)=>{const r:any=await knowledgeLineageCloud(identity,a.workspaceId,a.itemId);return textResult(`Current: ${(r.current||[]).map((x:any)=>x.name).join(', ')||'None'}\nVisible version nodes: ${(r.nodes||[]).length}\nDerived from: ${(r.derivedFrom||[]).map((x:any)=>x.name).join(', ')||'None'}`,{workspaceId:a.workspaceId,...r});});
  reg('get_knowledge_impact','Read OrbitFS knowledge impact','Show visible linked Knowledge Items and consumers affected by changing or removing a Knowledge Item.',{workspaceId:z.string(),itemId:z.string()},async(a:any)=>{const r:any=await knowledgeImpactCloud(identity,a.workspaceId,a.itemId);return textResult(`${r.item?.name||a.itemId}: ${r.affectedCount||0} visible dependencies · ${(r.usage||[]).length} consumers · ${(r.linkedItems||[]).length} linked items.`,{workspaceId:a.workspaceId,...r});});  reg('refresh_perms','Refresh OrbitFS permissions','Immediately reload the authenticated user system and workspace authority from Supabase.',{},async()=>{const r=await refreshPermissionsCloud(identity);await auditSystemCommand(identity,'refresh_perms',{workspaceCount:r.workspaceIds.length});return textResult('OrbitFS permissions refreshed.',r);});
  reg('get_user_roles','Get OrbitFS user roles','Return the authenticated user current system role and roles in accessible workspaces.',{workspaceId:z.string().optional()},async({workspaceId}:any)=>{const r=await refreshPermissionsCloud(identity),roles=workspaceId?r.workspaceRoles.filter((x:any)=>String(x.workspaceId)===String(workspaceId)):r.workspaceRoles;await auditSystemCommand(identity,'get_user_roles',{workspaceId:workspaceId||null});return textResult(`System role: ${r.systemRole}. Workspace roles: ${roles.length}.`,{systemRole:r.systemRole,workspaceRoles:roles});});
  reg('refresh_config','Refresh OrbitFS system configuration','System Owner/Admin only. Revalidate MCP licence, Supabase runtime, current permissions and active context state.',{},async()=>{requireAdmin(identity);await assertMcpLicensed();const [perms,status]=await Promise.all([refreshPermissionsCloud(identity),systemStatusCloud(identity)]);await auditSystemCommand(identity,'refresh_config',{workspaceCount:perms.workspaceIds.length});return textResult('OrbitFS system configuration refreshed.',{permissions:perms,status,refreshedAt:new Date().toISOString()});},rw);
  reg('global_sync','Force OrbitFS global sync','System Owner/Admin only. Re-sync OAuth client workspace grants and MCP runtime state with current Supabase authority.',{reason:z.string().min(3).max(500)},async({reason}:any)=>{requireAdmin(identity);const perms=await refreshPermissionsCloud(identity),db=getSupabaseAdmin();await db.from('mcp_clients').update({workspace_ids:perms.workspaceIds,last_seen_at:new Date().toISOString()}).eq('id',identity.clientId);await db.from('mcp_runtime_state').upsert({id:1,mode:'cloud',workspace_addon_active:true,connector_url:'https://orbitconvert-mcp-addon.vercel.app/mcp',service_status:'running',updated_at:new Date().toISOString()},{onConflict:'id'});await auditSystemCommand(identity,'global_sync',{reason,workspaceCount:perms.workspaceIds.length});return textResult('OrbitFS global sync completed.',{reason,permissions:perms,syncedAt:new Date().toISOString()});},rw);
  reg('studio_ui_state','Studio internal UI state','Internal app-only state endpoint for the Studio ChatGPT UI.',{workspaceId:z.string().optional()},async({workspaceId}:any)=>{const p:any=await chooseWorkspace(identity,workspaceId),state:any=await buildStudioUiState(identity,p.workspace.id);state.workspaces=p.workspaces.map((w:any)=>({id:String(w.id),name:w.name,status:w.status||'active'}));return textResult('Studio UI refreshed.',{workspaceId:p.workspace.id,uiState:state},{...appOnly,studioUiState:state});},ro,appOnly);
  reg('studio_set_mode','Set Studio writing mode','Set the current ChatGPT Studio session to normal writing or pure Vent Mode.',{workspaceId:z.string(),mode:z.enum(['normal','vent'])},async(a:any)=>{await chooseWorkspace(identity,a.workspaceId);setStudioModeCloud(identity,a.workspaceId,a.mode);const vent=await studioVentProfile(a.workspaceId,identity),state:any=await buildStudioUiState(identity,a.workspaceId);return textResult(a.mode==='vent'?'Studio Vent Mode enabled.':'Studio Vent Mode disabled.',{workspaceId:a.workspaceId,studioMode:a.mode,behaviourInstructions:a.mode==='vent'?vent.behaviourInstructions:'Studio normal writing mode is active.',ventConfig:vent.config,ventSaveLocation:vent.saveLocation,uiState:state},{...studioMeta,studioUiState:state});},rw,studioMeta);
  reg('studio_get_schema','Get Studio schema','Return current Studio journal/document types, statuses, metadata fields and supported features.',{workspaceId:z.string()},async({workspaceId}:any)=>{await chooseWorkspace(identity,workspaceId);return textResult('Studio schema loaded.',{workspaceId,schema:studioSchema()});});
  reg('studio_list_records','List Studio records','Find journals or documents. Returns compact metadata without loading full record bodies.',{workspaceId:z.string(),kind:z.enum(['journal','document','generated']).optional(),type:z.string().optional(),status:z.enum(['draft','final','archived']).optional(),tag:z.string().optional(),profileId:z.string().optional(),q:z.string().optional(),limit:z.number().int().min(1).max(200).optional()},async(a:any)=>{const p=new URLSearchParams({limit:String(a.limit||50)}),r=await listStudioDocuments(identity.user,a.workspaceId,p);let items=r.items||[];if(a.kind)items=items.filter((x:any)=>x.kind===a.kind);if(a.type)items=items.filter((x:any)=>x.subtype===a.type);if(a.status)items=items.filter((x:any)=>x.status===a.status);if(a.tag)items=items.filter((x:any)=>(x.metadata_json?.tags||[]).includes(a.tag));if(a.profileId)items=items.filter((x:any)=>(x.profile_ids||[]).map(String).includes(String(a.profileId)));if(a.q){const q=String(a.q).toLowerCase();items=items.filter((x:any)=>`${x.title} ${x.summary||''}`.toLowerCase().includes(q));}return textResult(`${items.length} Studio record${items.length===1?'':'s'} found.`,{workspaceId:a.workspaceId,records:items});});
  reg('studio_get_record','Get Studio record','Load one Studio journal/document body and its current approval state.',{workspaceId:z.string(),recordId:z.string()},async(a:any)=>{const r=await getStudioDocument(identity.user,a.workspaceId,a.recordId),approvals=await studioApprovals(identity,a.workspaceId,a.recordId);return textResult(`Loaded Studio ${r.item?.kind||'record'}: ${r.item?.title||a.recordId}`,{workspaceId:a.workspaceId,record:r.item,approvals:approvals.requests||[]});});  reg('studio_create_record','Create Studio journal or document','Create a one-shot Studio journal entry or document. Vent Mode preserves raw user wording and remains private unless explicitly submitted.',{workspaceId:z.string(),kind:z.enum(['journal','document']),type:z.string(),title:z.string().optional(),content:z.string().optional(),summary:z.string().optional(),entryDate:z.string().optional(),tags:z.array(z.string()).optional(),profileIds:z.array(z.string()).optional(),profileTargetId:z.string().optional(),profileSectionId:z.string().optional(),metadata:z.record(z.string(),z.any()).optional()},async(a:any)=>{await chooseWorkspace(identity,a.workspaceId);const vent=identity.studioModes?.[a.workspaceId]==='vent'||a.metadata?.studioMode==='vent',vp=vent?await studioVentProfile(a.workspaceId,identity):null;let title=a.title||'Untitled',metadata=a.metadata||{},tags=a.tags||[];if(vent&&vp){title=vp.formatTitle(title||String(a.content||'').split(/\r?\n/).find(Boolean)||'Untitled');tags=[...new Set(['vent',...tags])];metadata={...metadata,studioMode:'vent',preserveRaw:vp.config.retainRaw!==false,ownerOnly:true,userEyesOnly:true,category:metadata.category||'private'};}const r=await createStudioDocument(identity.user,a.workspaceId,{...a,kind:vent?'journal':a.kind,type:vent?'vent':a.type,title,tags,metadata,category:metadata.category,content:a.content||''});const state:any=await buildStudioUiState(identity,a.workspaceId);state.selectedRecord=r.item;state.initialView=(vent||a.kind==='journal')?'journals':'documents';return textResult(`${vent?'Vent':a.kind==='journal'?'Journal':'Document'} created: ${r.item.title}`,{workspaceId:a.workspaceId,record:r.item,uiState:state},{...studioMeta,studioUiState:state});},rw,studioMeta);
  reg('studio_update_record','Update Studio record','Edit an existing Studio journal/document. Content changes are revisioned by Studio.',{workspaceId:z.string(),recordId:z.string(),title:z.string().optional(),type:z.string().optional(),content:z.string().optional(),summary:z.string().optional(),entryDate:z.string().optional(),tags:z.array(z.string()).optional(),profileIds:z.array(z.string()).optional(),profileTargetId:z.string().optional(),profileSectionId:z.string().optional(),metadata:z.record(z.string(),z.any()).optional(),changeNote:z.string().optional()},async(a:any)=>{const body={...a,subtype:a.type};delete body.workspaceId;delete body.recordId;const r=await updateStudioDocument(identity.user,a.workspaceId,a.recordId,body),state:any=await buildStudioUiState(identity,a.workspaceId);state.selectedRecord=r.item;return textResult(`Studio record updated: ${r.item.title}`,{workspaceId:a.workspaceId,record:r.item,uiState:state},{...studioMeta,studioUiState:state});},rw,studioMeta);
  reg('studio_append','Append to Studio record or session','Append text to an existing Studio record or active Studio session.',{workspaceId:z.string(),recordId:z.string().optional(),sessionId:z.string().optional(),text:z.string(),changeNote:z.string().optional()},async(a:any)=>{const r:any=await appendStudioCloud(identity,a.workspaceId,a),state:any=await buildStudioUiState(identity,a.workspaceId);if(r.item?.content_text)state.selectedRecord=r.item;return textResult(a.sessionId||(!a.recordId&&r.item?.draft_content)?'Studio session updated.':`Appended to ${r.item?.title||'Studio record'}.`,{workspaceId:a.workspaceId,record:r.item?.content_text?r.item:null,session:r.item?.draft_content!==undefined?r.item:null,uiState:state},{...studioMeta,studioUiState:state});},rw,studioMeta);
  reg('studio_record_action','Change Studio record status or restore revision','Finalize, return to draft, archive, or restore a Studio record revision.',{workspaceId:z.string(),recordId:z.string(),action:z.enum(['finalize','draft','archive','restore-revision']),revisionNo:z.number().int().positive().optional()},async(a:any)=>{const r=a.action==='restore-revision'?await restoreStudioRevision(identity.user,a.workspaceId,a.recordId,Number(a.revisionNo)):await setStudioLifecycle(identity.user,a.workspaceId,a.recordId,a.action as any),state:any=await buildStudioUiState(identity,a.workspaceId);state.selectedRecord=r.item;return textResult(`Studio record ${a.action}.`,{workspaceId:a.workspaceId,record:r.item,uiState:state},{...studioMeta,studioUiState:state});},destructive,studioMeta);
  reg('studio_submit_approval','Submit Studio record for Library approval','Publish a Studio entry through the Base Library/Profile approval queue. This never bypasses approval.',{workspaceId:z.string(),recordId:z.string(),summary:z.string().optional(),reason:z.string().optional(),useRoutingSuggestions:z.boolean().optional(),routingSuggestionIndexes:z.array(z.number().int().min(0)).optional()},async(a:any)=>{const r=await submitStudioApproval(identity,a.workspaceId,a.recordId,a),state:any=await buildStudioUiState(identity,a.workspaceId);state.selectedRecord=(await getStudioDocument(identity.user,a.workspaceId,a.recordId)).item;state.approvals=(await studioApprovals(identity,a.workspaceId,a.recordId)).requests||[];return textResult('Studio entry submitted to Base approval.',{workspaceId:a.workspaceId,request:r.request,approvals:state.approvals,uiState:state},{...studioMeta,studioUiState:state});},rw,studioMeta);
  reg('studio_analyse_routing','Analyse Studio routing','Analyse a Studio entry and suggest its Base Library/Profile destinations using deterministic routing and Knowledge Setup.',{workspaceId:z.string(),recordId:z.string()},async(a:any)=>{const analysis:any=await analyseStudioRouting(identity,a.workspaceId,a.recordId),state:any=await buildStudioUiState(identity,a.workspaceId);state.selectedRecord=(await getStudioDocument(identity.user,a.workspaceId,a.recordId)).item;state.routingAnalysis=analysis;const top=analysis.suggestions?.[0];return textResult(top?`Suggested: ${top.label||top.kind} (${Math.round(Number(top.confidence||0)*100)}%).`:'No routing suggestion was produced.',{workspaceId:a.workspaceId,analysis,uiState:state},{...studioMeta,studioUiState:state});});
  reg('studio_list_revisions','List Studio record revisions','Return revision history for a selected Studio journal or document.',{workspaceId:z.string(),recordId:z.string()},async(a:any)=>{const r=await studioRevisions(identity.user,a.workspaceId,a.recordId);return textResult(`${r.items?.length||0} Studio revision${r.items?.length===1?'':'s'} found.`,{workspaceId:a.workspaceId,recordId:a.recordId,revisions:r.items||[]});});
  reg('studio_list_links','List Studio record links','Return structured links attached to a Studio journal or document.',{workspaceId:z.string(),recordId:z.string()},async(a:any)=>{const r=await listStudioLinks(identity,a.workspaceId,a.recordId);return textResult(`${r.items.length} Studio link${r.items.length===1?'':'s'} found.`,{workspaceId:a.workspaceId,recordId:a.recordId,links:r.items});});
  reg('studio_manage_link','Manage Studio record link','Add or remove a structured Studio link between a record and a profile, document, file or event.',{workspaceId:z.string(),action:z.enum(['add','remove']),recordId:z.string().optional(),linkId:z.string().optional(),targetType:z.enum(['profile','document','file','event']).optional(),targetId:z.string().optional(),relation:z.string().optional(),metadata:z.record(z.string(),z.any()).optional()},async(a:any)=>{const r=await manageStudioLink(identity,a.workspaceId,a),state:any=await buildStudioUiState(identity,a.workspaceId);return textResult(`Studio link ${a.action} complete.`,{workspaceId:a.workspaceId,result:r,uiState:state},{...studioMeta,studioUiState:state});},rw,studioMeta);
  reg('studio_create_document_from_record','Create Studio document from record','Turn an existing Studio record into a new document while preserving a traceable derived-from link.',{workspaceId:z.string(),sourceRecordId:z.string(),type:z.string().optional(),title:z.string().optional(),summary:z.string().optional(),content:z.string().optional(),tags:z.array(z.string()).optional(),profileIds:z.array(z.string()).optional()},async(a:any)=>{const r=await createDocumentFromRecord(identity,a.workspaceId,a),state:any=await buildStudioUiState(identity,a.workspaceId);state.initialView='documents';state.selectedRecord=r.record;return textResult(`Document created from ${r.sourceRecord.title}.`,{workspaceId:a.workspaceId,...r,uiState:state},{...studioMeta,studioUiState:state});},rw,studioMeta);
  reg('studio_session','Manage Studio journaling session','Start, append, finalize, inspect or discard a working Studio journaling session.',{workspaceId:z.string(),action:z.enum(['start','append','finalize','discard','list']),sessionId:z.string().optional(),title:z.string().optional(),type:z.string().optional(),content:z.string().optional(),entryDate:z.string().optional(),final:z.boolean().optional()},async(a:any)=>{const r=await studioSessionCloud(identity,a.workspaceId,a),state:any=await buildStudioUiState(identity,a.workspaceId);state.initialView='journals';return textResult(`Studio session ${a.action} complete.`,{workspaceId:a.workspaceId,...r,uiState:state},{...studioMeta,studioUiState:state});},rw,studioMeta);
  return server;
}

async function sharedRuntime(){
  if(!sharedRuntimePromise){
    sharedRuntimePromise=(async()=>{
      const server=createServer(identityProxy);
      const transport=new WebStandardStreamableHTTPServerTransport({sessionIdGenerator:undefined});
      await server.connect(transport);
      return{server,transport};
    })().catch((error)=>{sharedRuntimePromise=null;throw error;});
  }
  return sharedRuntimePromise;
}

export async function handleMcpAddonRequest(request:Request){
  try{
    const auth=await authenticateMcpAccessToken(request);await assertMcpLicensed();
    const identity=await createCloudMcpIdentity(request,auth.user,auth.scopes,auth.token);
    const {transport}=await sharedRuntime();
    return await requestIdentity.run(identity,()=>transport.handleRequest(request));
  }catch(error:any){
    const status=Number(error?.status||500),headers:any={'content-type':'application/json'};
    if(status===401)headers['www-authenticate']='Bearer resource_metadata="https://orbitconvert-mcp-addon.vercel.app/.well-known/oauth-protected-resource"';
    return new Response(JSON.stringify({error:String(error?.message||'MCP request failed'),code:String(error?.code||'MCP_ERROR')}),{status,headers});
  }
}